services:
  mongodb:
    image: "mongo:8.0.0-rc7"
    container_name: hotel-db
    ports:
      - "27017:27017"
    networks:
      - back-network
    volumes:
      - mongodb_data:/data/db  # Persist data
  api:
    build: .
    container_name: hotel-api
    depends_on:
      - mongodb
    ports:
      - "4000:4000"
    networks:
      - back-network
networks:
  back-network:
    driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: "172.16.0.0/24"
    #       gateway: "172.16.0.1"
volumes:
  mongodb_data:  # Named volume for MongoDB persistence
